// Lightweight i18n helper, shared by popup.ts, background.ts and content.ts.
//
// Source of truth: _locales/<lang>/messages.json — the same files Chrome's own
// chrome.i18n uses for manifest fields (extName, extDescription, actionTitle).
// We additionally read them ourselves at runtime (via fetch, since chrome.i18n
// only exposes the browser's own UI language and can't be told to use a
// different language than the browser at runtime — see README).
//
// A contributor adds support for a new language by:
//   1. Creating _locales/<code>/messages.json (copy an existing one, translate
//      "message" values, set "languageSelfName" to that language's own native name).
//   2. Running `npm run sync-languages` (regenerates _locales/languages.json,
//      the small index this file reads to know which languages exist).
// No other file needs to change — SUPPORTED_LANGUAGES, the language dropdown in
// the popup, and every t() call pick it up automatically.

import type { LanguageInfo, TranslationVars } from './types';

export const DEFAULT_LANGUAGE = 'en';

export let SUPPORTED_LANGUAGES: string[] = [DEFAULT_LANGUAGE];
export let LANGUAGE_LIST: LanguageInfo[] = [{ code: DEFAULT_LANGUAGE, name: 'English' }];

type TranslationDict = Record<string, string>;
interface RawMessage {
  message?: string;
  description?: string;
}
type RawMessages = Record<string, RawMessage>;

const TRANSLATIONS_CACHE: Record<string, TranslationDict> = {};
let i18nReadyPromise: Promise<void> | null = null;

function fetchExtensionJSON<T>(path: string): Promise<T> {
  return fetch(chrome.runtime.getURL(path)).then((res) => {
    if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
    return res.json() as Promise<T>;
  });
}

// chrome.i18n messages.json shape ({key: {message, description?}}) -> flat {key: message}
function flattenMessages(raw: RawMessages | undefined): TranslationDict {
  const flat: TranslationDict = {};
  Object.keys(raw || {}).forEach((key) => {
    const message = raw?.[key]?.message;
    if (typeof message === 'string') flat[key] = message;
  });
  return flat;
}

export function loadTranslations(lang: string): Promise<TranslationDict> {
  if (TRANSLATIONS_CACHE[lang]) return Promise.resolve(TRANSLATIONS_CACHE[lang]);
  return fetchExtensionJSON<RawMessages>(`_locales/${lang}/messages.json`)
    .then((raw) => { TRANSLATIONS_CACHE[lang] = flattenMessages(raw); return TRANSLATIONS_CACHE[lang]; })
    .catch((e) => {
      console.error(`i18n: failed to load "${lang}" dictionary`, e);
      TRANSLATIONS_CACHE[lang] = TRANSLATIONS_CACHE[lang] || {};
      return TRANSLATIONS_CACHE[lang];
    });
}

// One-time bootstrap: discover which languages exist (_locales/languages.json,
// generated by sync-languages.ps1) and preload the fallback dictionary.
// Memoized — safe to call from every entry point (background.ts, popup.ts, content.ts).
export function ensureI18nReady(): Promise<void> {
  if (!i18nReadyPromise) {
    i18nReadyPromise = fetchExtensionJSON<LanguageInfo[]>('_locales/languages.json')
      .then((list) => {
        if (Array.isArray(list) && list.length) {
          LANGUAGE_LIST = list;
          SUPPORTED_LANGUAGES = list.map((l) => l.code);
        }
      })
      .catch((e) => {
        console.error('i18n: failed to load _locales/languages.json, falling back to', SUPPORTED_LANGUAGES, e);
      })
      .then(() => loadTranslations(DEFAULT_LANGUAGE))
      .then(() => undefined);
  }
  return i18nReadyPromise;
}

function detectSystemLanguage(): string {
  let uiLang = '';
  try {
    if (typeof chrome !== 'undefined' && chrome.i18n && chrome.i18n.getUILanguage) {
      uiLang = chrome.i18n.getUILanguage();
    }
  } catch (e) { /* ignore */ }
  if (!uiLang && typeof navigator !== 'undefined' && navigator.language) {
    uiLang = navigator.language;
  }
  uiLang = uiLang.toLowerCase();
  const match = SUPPORTED_LANGUAGES.find((code) => uiLang.startsWith(code));
  return match || DEFAULT_LANGUAGE;
}

export function resolveLanguage(pref?: string | null): string {
  const lang = (!pref || pref === 'system') ? detectSystemLanguage() : pref;
  return SUPPORTED_LANGUAGES.includes(lang) ? lang : DEFAULT_LANGUAGE;
}

// Ensures languages are discovered, resolves the preferred one, and guarantees
// its dictionary is cached — await this before any t() call chain, then t()
// itself can stay synchronous.
export function resolveAndLoadLanguage(pref?: string | null): Promise<string> {
  return ensureI18nReady()
    .then(() => resolveLanguage(pref))
    .then((lang) => loadTranslations(lang).then(() => lang));
}

// Convenience wrapper matching the callback-style API used throughout the codebase.
export function getLanguage(callback: (lang: string) => void): void {
  chrome.storage.local.get(['language'], (result) => {
    resolveAndLoadLanguage(result.language).then(callback);
  });
}

export function t(lang: string, key: string, vars?: TranslationVars): string {
  const dict = TRANSLATIONS_CACHE[lang] || TRANSLATIONS_CACHE[DEFAULT_LANGUAGE] || {};
  const fallbackDict = TRANSLATIONS_CACHE[DEFAULT_LANGUAGE] || {};
  let str = dict[key] || fallbackDict[key] || key;
  if (vars) {
    Object.keys(vars).forEach((k) => { str = str.replace(`{${k}}`, String(vars[k])); });
  }
  return str;
}

// DOM pages only (popup.html) — applies translations to static markup.
export function applyStaticI18n(lang: string, root?: ParentNode): void {
  const scope: ParentNode = root || document;
  scope.querySelectorAll('[data-i18n]').forEach((el) => {
    el.textContent = t(lang, el.getAttribute('data-i18n') || '');
  });
  scope.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
    (el as HTMLInputElement).placeholder = t(lang, el.getAttribute('data-i18n-placeholder') || '');
  });
  scope.querySelectorAll('[data-i18n-title]').forEach((el) => {
    (el as HTMLElement).title = t(lang, el.getAttribute('data-i18n-title') || '');
  });
}
