// Lightweight i18n helper, shared by popup.js, background.js and content.js.
//
// Source of truth: _locales/<lang>/messages.json — the same files Chrome's own
// chrome.i18n uses for manifest fields (extName, extDescription, actionTitle).
// We additionally read them ourselves at runtime (via fetch, since chrome.i18n
// only exposes the browser's own UI language and can't be told to use a
// different language than the browser at runtime — see README).
//
// A contributor adds support for a new language by:
//   1. Creating _locales/<code>/messages.json (copy an existing one, translate
//      "message" values, set "languageSelfName" to that language's own native name).
//   2. Running `npm run sync-languages` (regenerates _locales/languages.json,
//      the small index this file reads to know which languages exist).
// No other file needs to change — SUPPORTED_LANGUAGES, the language dropdown in
// the popup, and every t() call pick it up automatically.

const DEFAULT_LANGUAGE = 'en';

let SUPPORTED_LANGUAGES = [DEFAULT_LANGUAGE];
let LANGUAGE_LIST = [{ code: DEFAULT_LANGUAGE, name: 'English' }];

const TRANSLATIONS_CACHE = {};
let i18nReadyPromise = null;

function fetchExtensionJSON(path) {
  return fetch(chrome.runtime.getURL(path)).then((res) => {
    if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
    return res.json();
  });
}

// chrome.i18n messages.json shape ({key: {message, description?}}) -> flat {key: message}
function flattenMessages(raw) {
  const flat = {};
  Object.keys(raw || {}).forEach((key) => {
    if (raw[key] && typeof raw[key].message === 'string') flat[key] = raw[key].message;
  });
  return flat;
}

function loadTranslations(lang) {
  if (TRANSLATIONS_CACHE[lang]) return Promise.resolve(TRANSLATIONS_CACHE[lang]);
  return fetchExtensionJSON(`_locales/${lang}/messages.json`)
    .then((raw) => { TRANSLATIONS_CACHE[lang] = flattenMessages(raw); return TRANSLATIONS_CACHE[lang]; })
    .catch((e) => {
      console.error(`i18n: failed to load "${lang}" dictionary`, e);
      TRANSLATIONS_CACHE[lang] = TRANSLATIONS_CACHE[lang] || {};
      return TRANSLATIONS_CACHE[lang];
    });
}

// One-time bootstrap: discover which languages exist (_locales/languages.json,
// generated by scripts/sync-languages) and preload the fallback dictionary.
// Memoized — safe to call from every entry point (background.js, popup.js, content.js).
function ensureI18nReady() {
  if (!i18nReadyPromise) {
    i18nReadyPromise = fetchExtensionJSON('_locales/languages.json')
      .then((list) => {
        if (Array.isArray(list) && list.length) {
          LANGUAGE_LIST = list;
          SUPPORTED_LANGUAGES = list.map((l) => l.code);
        }
      })
      .catch((e) => {
        console.error('i18n: failed to load _locales/languages.json, falling back to', SUPPORTED_LANGUAGES, e);
      })
      .then(() => loadTranslations(DEFAULT_LANGUAGE));
  }
  return i18nReadyPromise;
}

function detectSystemLanguage() {
  let uiLang = '';
  try {
    if (typeof chrome !== 'undefined' && chrome.i18n && chrome.i18n.getUILanguage) {
      uiLang = chrome.i18n.getUILanguage();
    }
  } catch (e) { /* ignore */ }
  if (!uiLang && typeof navigator !== 'undefined' && navigator.language) {
    uiLang = navigator.language;
  }
  uiLang = uiLang.toLowerCase();
  const match = SUPPORTED_LANGUAGES.find((code) => uiLang.startsWith(code));
  return match || DEFAULT_LANGUAGE;
}

function resolveLanguage(pref) {
  const lang = (!pref || pref === 'system') ? detectSystemLanguage() : pref;
  return SUPPORTED_LANGUAGES.includes(lang) ? lang : DEFAULT_LANGUAGE;
}

// Ensures languages are discovered, resolves the preferred one, and guarantees
// its dictionary is cached — await this before any t() call chain, then t()
// itself can stay synchronous.
function resolveAndLoadLanguage(pref) {
  return ensureI18nReady()
    .then(() => resolveLanguage(pref))
    .then((lang) => loadTranslations(lang).then(() => lang));
}

// Convenience wrapper matching the old callback-style API used throughout the codebase.
function getLanguage(callback) {
  chrome.storage.local.get(['language'], (result) => {
    resolveAndLoadLanguage(result.language).then(callback);
  });
}

function t(lang, key, vars) {
  const dict = TRANSLATIONS_CACHE[lang] || TRANSLATIONS_CACHE[DEFAULT_LANGUAGE] || {};
  const fallbackDict = TRANSLATIONS_CACHE[DEFAULT_LANGUAGE] || {};
  let str = dict[key] || fallbackDict[key] || key;
  if (vars) {
    Object.keys(vars).forEach((k) => { str = str.replace(`{${k}}`, vars[k]); });
  }
  return str;
}

// DOM pages only (popup.html) — applies translations to static markup.
function applyStaticI18n(lang, root) {
  root = root || document;
  root.querySelectorAll('[data-i18n]').forEach((el) => {
    el.textContent = t(lang, el.getAttribute('data-i18n'));
  });
  root.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
    el.placeholder = t(lang, el.getAttribute('data-i18n-placeholder'));
  });
  root.querySelectorAll('[data-i18n-title]').forEach((el) => {
    el.title = t(lang, el.getAttribute('data-i18n-title'));
  });
}
